server:
  port: 8070
  # 开启 gzip 压缩
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    # 超过 1KB 即开启压缩
    min-response-size: 1024
  # 开启 http2 支持 只在https下起作用
  http2:
    enabled: true

spring:
  jpa:
    database: MYSQL
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  #数据源
  datasource:
    url: jdbc:mysql://localhost:3306/music_story?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    druid:
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filter:
        stat:
          merge-sql: true
          db-type: mysql
          slow-sql-millis: 1000
          enabled: true
          log-slow-sql: true
        #配置 wall filter
        wall:
          db-type: mysql
          enabled: true
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  #邮件配置
  mail:
    host: smtp.qq.com
    username: 531237716@qq.com
    password: ENC(tU3XEcH8VDNaNRNkGkKu5fvCRZK9Fv3Kf4Ii8+fC81s=)
    default-encoding: UTF-8
  # Redis 配置
  redis:
    host: 127.0.0.1
    port: 6379
    password:

jasypt:
  encryptor:
    password: ngCly
#私人密钥配置
upload:
  accessKey: ENC(ormo2Qg4s+fXW8qyJcwWdkH/MopGFUBTxsbVeJoOkuQ=)
  secretKey: ENC(aHUGIXAeXajFvMtPdmI2RZAnwIFU+7umvjk/ea+eJCThNdZKmmHFnQ==)
appcode: ENC(HaqiZpNoRrldOYjmhSw1mjtjOVV9Vrfh0bid7Ksz5c5rvgWBs33JEW95khhTgloc)